#!/usr/bin/env bash

set -euxo pipefail

touch ~/.hushlogin

sed -i -E 's/#?PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config

mkdir -p \
  /etc/systemd/system/openordinals.service.d 

hostnamectl set-hostname ordinals.org

apt-get install --yes \
  acl \
  clang \
  libsqlite3-dev\
  libssl-dev \
  pkg-config \
  ufw \
  caddy \
  vim

ufw default allow outgoing
ufw default deny incoming

ufw allow 8080
ufw allow http
ufw allow https
ufw allow ssh

ufw --force enable

mkdir -p /var/lib/openordinals
mkdir -p /var/www/openordinals 

id --user openordinals || useradd --system openordinals

cp deploy/openordinals.service /etc/systemd/system/
systemctl daemon-reload
systemctl enable openordinals
systemctl restart openordinals
