#!/usr/bin/env bash

set -euxo pipefail

touch ~/.hushlogin

sed -i -E 's/#?PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config

mkdir -p \
  /etc/systemd/system/inscribingamsterdam.service.d 

hostnamectl set-hostname inscribingamsterdam.com

apt-get install --yes \
  acl \
  clang \
  libsqlite3-dev\
  libssl-dev \
  pkg-config \
  ufw \
  vim

ufw default allow outgoing
ufw default deny incoming

ufw allow 8080
ufw allow http
ufw allow https
ufw allow ssh

ufw --force enable

mkdir -p /var/lib/inscribingamsterdam

id --user inscribingamsterdam || useradd --system inscribingamsterdam

cp deploy/inscribingamsterdam.service /etc/systemd/system/
systemctl daemon-reload
systemctl enable inscribingamsterdam
systemctl restart inscribingamsterdam
